[build]
target = "riscv32imac-esp-espidf"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Ensure ESP-IDF environment is sourced
ESP_IDF_VERSION = { value = "v5.1" }
